_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "3":
                - 3
                - 8
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.10
            "8":
                - 3
                - 5
            "10":
                - 9
                - 17
            "12": 0.19.10
            "13": windows-amd64
batch_size:
    value: 32
dataset:
    value: prices-split-adjusted.csv
epochs:
    value: 10
learning_rate:
    value: 0.001
model:
    value: GRU
sequence_length:
    value: 30
